export const AUTH_SENT_STAFF_TOKEN = "AUTH_SENT_STAFF_TOKEN";
export const AUTH_SENT_STAFF_TOKEN_FAILED = "AUTH_SENT_STAFF_TOKEN_FAILED";
export const STAFF_REG_TOKEN_CONFIRMED = "STAFF_REG_TOKEN_CONFIRMED";
export const STAFF_REG_TOKEN_CONFIRM_FAILED = "STAFF_REG_TOKEN_CONFIRM_FAILED";
export const STAFF_REGISTRATION_SUCCEEDED = "STAFF_REGISTRATION_SUCCEEDED";
export const STAFF_REGISTRATION_FAILED = "STAFF_REGISTRATION_FAILED";
export const STAFF_LOGIN_SUCCEEDED = "STAFF_LOGIN_SUCCEEDED";
export const STAFF_LOGIN_FAILED = "STAFF_LOGIN_FAILED";
export const STAFF_LOGED_OUT = "STAFF_LOGED_OUT";
export const STAFF_FETCH_SUCCEEDED = "STAFF_FETCH_SUCCEEDED";
export const STAFF_FETCH_FAILED = "STAFF_FETCH_FAILED";
export const IS_FETCHING_STAFF = "IS_FETCHING_STAFF";
export const STAFF_DATA_UPDATE_SUCCEEDED = "STAFF_DATA_UPDATE_SUCCEEDED";
export const STAFF_DATA_UPDATE_FAILED = "STAFF_DATA_UPDATE_FAILED";
export const IS_UPDATING_STAFF_DATA = "IS_UPDATING_STAFF_DATA";

export const ALL_STAFFS_FETCH_SUCCEEDED = "ALL_STAFFS_FETCH_SUCCEEDED";
export const ALL_STAFFS_FETCH_FAILED = "ALL_STAFFS_FETCH_FAILED";
export const IS_FETCHING_ALL_STAFFS = "IS_FETCHING_ALL_STAFFS";

export const NEW_STUDENT_REGISTRATION_SUCCEEDED = "NEW_STUDENT_REGISTRATION_SUCCEEDED";
export const NEW_STUDENT_REGISTRATION_FAILED = "NEW_STUDENT_REGISTRATION_FAILED";
export const ALL_STUDENTS_FETCH_SUCCEEDED = "ALL_STUDENTS_FETCH_SUCCEEDED";
export const IS_FETCHING_STUDENTS = "IS_FETCHING_STUDENTS";
export const ALL_STUDENTS_FETCH_FAILED = "ALL_STUDENTS_FETCH_FAILED";
export const FETCHING_A_STUDENT_SUCCEEDED = "FETCHING_A_STUDENT_SUCCEEDED";
export const IS_FETCHING_A_STUDENT = "IS_FETCHING_A_STUDENTS";
export const FETCHING_A_STUDENT_FAILED = "FETCHING_A_STUDENT_FAILED";
export const UPDATE_STUDENT_DATA_SUCCEEDED = "UPDATE_STUDENT_DATA_SUCCEEDED";
export const UPDATE_STUDENT_DATA_FAILED = "UPDATE_STUDENT_DATA_FAILED";
export const CONFIRM_STAFF_EMAIL_SUCCEEDED = "CONFIRM_STAFF_EMAIL_SUCCEEDED";
export const CONFIRM_STAFF_EMAIL_FAILED = "CONFIRM_STAFF_EMAIL_FAILED";
export const IS_CONFIRMING_STAFF_EMAIL = "IS_CONFIRMING_STAFF_EMAIL";
export const PASSWORD_RESET_SUCCESSFUL = "PASSWORD_RESET_SUCCESSFUL";
export const PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED";
export const CREATE_RESULT_MANAGER_SUCCEEDED = "CREATE_RESULT_MANAGER_SUCCEEDED";
export const CREATE_RESULT_MANAGER_FAILED = "CREATE_RESULT_MANAGER_FAILED";

export const ALL_CURRENT_STUDENTS_FETCH_SUCCEEDED = "ALL_CURRENT_STUDENTS_FETCH_SUCCEEDED";
export const ALL_CURRENT_STUDENTS_FETCH_FAILED = "ALL_CURRENT_STUDENTS_FETCH_FAILED";

export const GRADEBOOK_SUCCEEDED = "GRADEBOOK_SUCCEEDED";
export const GRADEBOOK_FAILED = "GRADEBOOK_FAILED";

export const GRADEBOOK_SCORE_UPDATE_SUCCEEDED = "GRADEBOOK_SCORE_UPDATE_SUCCEEDED";
export const GRADEBOOK_SCORE_UPDATE_FAILED = "GRADEBOOK_SCORE_UPDATE_FAILED";
export const IS_UPDATING_GRADEBOOK_SCORE = "IS_UPDATING_GRADEBOOK_SCORE";

export const COMPUTE_RESULTS_SUCCEEDED = "COMPUTE_RESULTS_SUCCEEDED";
export const COMPUTE_RESULTS_FAILED = "COMPUTE_RESULTS_FAILED";
export const IS_COMPUTING_RESULTS = "IS_COMPUTING_RESULTS";
export const FETCH_RESULTSHEET_SUCCEEDED = "FETCH_RESULTSHEET_SUCCEEDED";
export const FETCH_RESULTSHEET_FAILED = "FETCH_RESULTSHEET_FAILED";
export const IS_FETCHING_RESULTSHEET = "IS_FETCHING_RESULTSHEET";

export const UPDATE_STAFF_ROLES_SUCCEEDED = "UPDATE_STAFF_ROLES_SUCCEEDED";
export const UPDATE_STAFF_ROLES_FAILED = "UPDATE_STAFF_ROLES_FAILED";

export const UPDATE_STAFF_SUBJECTS_SUCCEEDED = "UPDATE_STAFF_SUBJECTS_SUCCEEDED";
export const UPDATE_STAFF_SUBJECTS_FAILED = "UPDATE_STAFF_SUBJECTS_FAILED";

export const STUDENTS_IN_CLASS_PER_TERM_SUCCEEDED = "STUDENTS_IN_CLASS_PER_TERM_SUCCEEDED";
export const STUDENTS_IN_CLASS_PER_TERM_FAILED = "STUDENTS_IN_CLASS_PER_TERM_FAILED";
export const IS_FETCHING_STUDENTS_CLASS = "IS_FETCHING_STUDENTS_CLASS";

export const DELETE_STUDENT_FROM_CLASS_SUCCEEDED = "DELETE_STUDENT_FROM_CLASS_SUCCEEDED";
export const DELETE_STUDENT_FROM_CLASS_FAILED = "DELETE_STUDENT_FROM_CLASS_FAILED";

export const STUDENTS_SUBJECTS_PER_TERM_SUCCEEDED = "STUDENTS_SUBJECTS_PER_TERM_SUCCEEDED";
export const STUDENTS_SUBJECTS_PER_TERM_FAILED = "STUDENTS_SUBJECTS_PER_TERM_FAILED";
export const IS_FETCHING_STUDENTS_SUBJECTS = "IS_FETCHING_STUDENTS_SUBJECTS";

export const DELETE_SUBJECT_FROM_CLASS_SUCCEEDED = "DELETE_SUBJECT_FROM_CLASS_SUCCEEDED";
export const DELETE_SUBJECT_FROM_CLASS_FAILED = "DELETE_SUBJECT_FROM_CLASS_FAILED";

export const FETCH_SCRATCH_CARDS_SUCCEEDED = "FETCH_SCRATCH_CARDS_SUCCEEDED";
export const FETCH_SCRATCH_CARDS_FAILED = "FETCH_SCRATCH_CARDS_FAILED";
export const IS_FETCHING_SCRATCH_CARDS = "IS_FETCHING_SCRATCH_CARDS";
export const GENERATE_SCRATCH_CARDS_SUCCEEDED = "GENERATE_SCRATCH_CARDS_SUCCEEDED";
export const GENERATE_SCRATCH_CARDS_FAILED = "GENERATE_SCRATCH_CARDS_FAILED";
